/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportcardprogram;

/**
 *
 * @author salat5228
 */
import java.text.NumberFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new java.awt.Label();
        name1 = new javax.swing.JTextField();
        studnum1 = new javax.swing.JTextField();
        Title1 = new java.awt.Label();
        Title2 = new java.awt.Label();
        Title3 = new java.awt.Label();
        subjectA = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        Title4 = new java.awt.Label();
        Title5 = new java.awt.Label();
        totalAvg = new javax.swing.JTextField();
        subjectC = new javax.swing.JTextField();
        subjectB = new javax.swing.JTextField();
        subjectD = new javax.swing.JTextField();
        avgA = new javax.swing.JTextField();
        avgC = new javax.swing.JTextField();
        avgB = new javax.swing.JTextField();
        avgD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(532, 688));

        Title.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        Title.setPreferredSize(new java.awt.Dimension(38, 72));
        Title.setText("Add Student");

        name1.setBackground(new java.awt.Color(204, 204, 204));
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });

        studnum1.setBackground(new java.awt.Color(204, 204, 204));
        studnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnum1ActionPerformed(evt);
            }
        });

        Title1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Title1.setPreferredSize(new java.awt.Dimension(38, 72));
        Title1.setText("Student Name");

        Title2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Title2.setPreferredSize(new java.awt.Dimension(38, 72));
        Title2.setText("Total Average:");

        Title3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Title3.setPreferredSize(new java.awt.Dimension(38, 72));
        Title3.setText("Average");

        subjectA.setBackground(new java.awt.Color(204, 204, 204));
        subjectA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectAActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Input Student");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        Title4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Title4.setPreferredSize(new java.awt.Dimension(38, 72));
        Title4.setText("Number");

        Title5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Title5.setPreferredSize(new java.awt.Dimension(38, 72));
        Title5.setText("Subject");

        totalAvg.setEditable(false);
        totalAvg.setBackground(new java.awt.Color(204, 204, 204));
        totalAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAvgActionPerformed(evt);
            }
        });

        subjectC.setBackground(new java.awt.Color(204, 204, 204));
        subjectC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCActionPerformed(evt);
            }
        });

        subjectB.setBackground(new java.awt.Color(204, 204, 204));
        subjectB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectBActionPerformed(evt);
            }
        });

        subjectD.setBackground(new java.awt.Color(204, 204, 204));
        subjectD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectDActionPerformed(evt);
            }
        });

        avgA.setBackground(new java.awt.Color(204, 204, 204));
        avgA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgAActionPerformed(evt);
            }
        });

        avgC.setBackground(new java.awt.Color(204, 204, 204));
        avgC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgCActionPerformed(evt);
            }
        });

        avgB.setBackground(new java.awt.Color(204, 204, 204));
        avgB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgBActionPerformed(evt);
            }
        });

        avgD.setBackground(new java.awt.Color(204, 204, 204));
        avgD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avgA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avgB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(totalAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Title5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subjectA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subjectB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jToggleButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(avgC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(avgD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(subjectC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(subjectD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(Title5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subjectA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subjectC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subjectB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subjectD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(avgA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(avgC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(avgB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(avgD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void studnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnum1ActionPerformed

    private void subjectAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectAActionPerformed

    }//GEN-LAST:event_subjectAActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
   int average;
    int subjectAverageA = Integer.parseInt(avgA.getText());
    int subjectAverageB = Integer.parseInt(avgB.getText());
    int subjectAverageC = Integer.parseInt(avgC.getText());
    int subjectAverageD = Integer.parseInt(avgD.getText());
    average = (subjectAverageA+subjectAverageB+subjectAverageC+subjectAverageD)/4;
    String newAvg = average+" ";
    totalAvg.setText(newAvg);
        DefaultTableModel model = (DefaultTableModel) ReportCardProgram.jTable1.getModel();
    model.addRow(new Object[]{name1.getText(), totalAvg.getText(), subjectA.getText() + ": " + avgA.getText(),
    subjectB.getText() + ": " + avgB.getText(),
    subjectC.getText() + ": " + avgC.getText(),
            subjectD.getText() + ": " + avgD.getText()});
    
    this.dispose();

        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void totalAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAvgActionPerformed
    
    }//GEN-LAST:event_totalAvgActionPerformed

    private void subjectCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCActionPerformed

    private void subjectBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectBActionPerformed

    private void subjectDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectDActionPerformed

    private void avgAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgAActionPerformed

    }//GEN-LAST:event_avgAActionPerformed

    private void avgCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgCActionPerformed

    private void avgBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgBActionPerformed

    private void avgDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    NumberFormat format = NumberFormat.getInstance();
    NumberFormatter formatter = new NumberFormatter(format);
    formatter.setValueClass(Integer.class);
    formatter.setMinimum(0);
    formatter.setMaximum(Integer.MAX_VALUE);
    // If you want the value to be committed on each keystroke instead of focus lost
    formatter.setCommitsOnValidEdit(true);
    JFormattedTextField field = new JFormattedTextField(formatter);

    JOptionPane.showMessageDialog(null, field);

    // getValue() always returns something valid
    System.out.println(field.getValue());
    
    

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Title;
    private java.awt.Label Title1;
    private java.awt.Label Title2;
    private java.awt.Label Title3;
    private java.awt.Label Title4;
    private java.awt.Label Title5;
    private javax.swing.JTextField avgA;
    private javax.swing.JTextField avgB;
    private javax.swing.JTextField avgC;
    private javax.swing.JTextField avgD;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField studnum1;
    private javax.swing.JTextField subjectA;
    private javax.swing.JTextField subjectB;
    private javax.swing.JTextField subjectC;
    private javax.swing.JTextField subjectD;
    private javax.swing.JTextField totalAvg;
    // End of variables declaration//GEN-END:variables
}
